### ISSUE TITLE
How to generate secret ?

### ISSUE THREAD

**Issue by unrealwill** [susam/toytotp#1]
Is the 'Getting Started' safe to follow ? 
Won't copy-pasting with the provided secret-key and following with google authenticator compromise my google account ?

**Comment by susam** [comment]
The secret key provided in this project is only for demo and testing purpose. Of course, it should not be used with any real account because anyone can copy this key and generate the same TOTPs as you do. 🙂

Usually, when we sign up for TOTP-based two factor authentication on any website, that website generates a secret-key, encodes it into a QR code, and asks us (the user) to scan the QR code with a software-based authenticator app such as Google Authenticator on our mobile phone. In this manner, the website and the authenticator app establish the same shared secret key and they can both generate the same TOTP values.

**Comment by unrealwill** [comment]
Can you add a "step 0 : choose a secret" with a warning not to pick your default example ?
Because it seems like your project could be used to spearfish novice hackers.

I am not familiar with google authenticator but I was wondering how bad was it to follow your tutorial with a public secret : 
if you manage to get convince someone with known email to follow the tutorial with the provided example, can you then use a google reset password (or pair your account with a brand new google authenticator app) and enter the verification code (you can compute) to steal the account ?

**Comment by jaywgraves** [comment]
@unrealwill  As the author mentioned, the service provides the secret to you (as noted, mostly in the form of a QR code) because both (you and the service) need the same secret to generate the right codes based on the current time.  You never get to choose, it is provided to you.

There is no security issue with his example usage because those codes are not attached to anyone's service.  I could load his code into my Google Authenticator app on my Android phone and nothing would be harmed.  I wouldn't be able to use that code for any account (google, dropbox, github, etc) because those services have different secrets that were generated at the time I set them up. 

To use this for real, you need to provide the secret that your service gave you.  But that being said I am pretty sure this is just sample code, not something that anyone should actually use because you have to keep your secret out in the open and provide it to the script every time you want to use it.  In most production ready TOTP apps, the secret for each account is not visible after it is loaded, only the resultant time code is available.

Also there is nothing magical about 'Google Authenticator' it is just an application that uses a standard algorithm that happens to work with Google.  It is not tied to your Google account directly and can be used for other services using the same TOTP algorithm.
