### ISSUE TITLE
module 'hmac' has no attribute 'digest'

### ISSUE THREAD

**Issue by Zibri** [susam/toytotp#2]
Traceback (most recent call last):
  File "totp.py", line 26, in <module>
    print(totp(secret))
  File "totp.py", line 21, in totp
    return hotp(secret, int(time.time() / interval))
  File "totp.py", line 14, in hotp
    mac = hmac.digest(secret_bytes, counter_bytes, algo)
AttributeError: module 'hmac' has no attribute 'digest'

**Comment by susam** [comment]
Thank you, @Zibri, for reporting this issue. The `hmac.digest()` function is available since Python 3.7 only. The `hmac.digest()` documentation [here](https://docs.python.org/3.7/library/hmac.html#hmac.digest) mentions:

> *New in version 3.7.*

This issue has been fixed in commit 56ef9a6d6d9aa0545f9c0f352a34ca8406607d8d by using `hmac.new().digest()` instead, so that this code can work with earlier versions of Python too.
